services:
  router:
    build: .
    container_name: router
    privileged: true  # Necesario para iptables y sysctl
    networks:
      router_router_net:
        ipv4_address: 172.10.0.2
      services_net:
        ipv4_address: 172.20.0.2
      production_net:
        ipv4_address: 172.30.0.2
      development_net:
        ipv4_address: 172.40.0.2
    volumes:
      - ./dhcpd.conf:/etc/dhcp/dhcpd.conf
      - ./iptables_rules.sh:/iptables_rules.sh
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - |
        # Configurar iptables para usar la versión legacy
        update-alternatives --set iptables /usr/sbin/iptables-legacy
        update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

        # Configuración de DHCP
        touch /var/lib/dhcp/dhcpd.leases
        chmod 644 /var/lib/dhcp/dhcpd.leases
        echo "1" > /proc/sys/net/ipv4/ip_forward
        dhcpd -cf /etc/dhcp/dhcpd.conf -f &  # Arrancar DHCP en segundo plano

        # Aplicar reglas de iptables
        chmod +x /iptables_rules.sh
        sh /iptables_rules.sh

        tail -f /dev/null  # Mantiene el contenedor activo



networks:
  router_router_net:
    external: true
  services_net:
    external: true
  production_net:
    external: true
  development_net:
    external: true
