uid = nobody
gid = nogroup
use chroot = no
max connections = 4
log file = /var/log/rsyncd.log
pid file = /var/run/rsyncd.pid

[backups]
    path = /srv/nas/backups
    comment = Carpeta de respaldo
    read only = no
    list = yes
