FROM debian:bookworm

# Instalar dependencias en una sola ejecución
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    bash \
    isc-dhcp-client \
    iputils-ping \
    bind9 \
    net-tools \
    samba \
    cron \
    rsync \
    iproute2 \
    --no-install-recommends \
    -o Dpkg::Options::="--force-confold" && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copiar script de arranque
COPY ./backups/rsyncd.conf /services/backups/rsyncd.conf
COPY ./backups/smb.conf /etc/samba/smb.conf
COPY ./backups/start.sh /start.sh
RUN chmod +x /start.sh

# Comando de inicio
CMD ["/start.sh"]